// Localized blog content. Falls back to English (posts.ts) for any missing language/slug.
// Body block STRUCTURE must mirror the English post (same order & rate pairs); only text is translated.
import type { Block } from './posts'

export interface LocalizedPost {
  title: string
  description: string
  excerpt: string
  body: Block[]
}

// Blog UI strings per language.
export const BLOG_UI: Record<string, {
  indexTitle: string; indexIntro: string; metaTitle: string; metaDesc: string
  allPosts: string; keepReading: string; minRead: string
}> = {
  en: {
    indexTitle: 'The Multi Converter Blog',
    indexIntro: 'Plain-English guides on currency conversion, exchange rates, and getting the real value of your money.',
    metaTitle: 'Blog — Currency Conversion Tips & Exchange Rate Guides | Multi Converter',
    metaDesc: 'Guides on currency conversion, exchange rates and getting the best value for your money — from the team behind Multi Converter.',
    allPosts: 'All posts', keepReading: 'Keep reading', minRead: 'min read',
  },
  es: {
    indexTitle: 'El blog de Multi Converter',
    indexIntro: 'Guías sencillas sobre conversión de divisas, tipos de cambio y cómo obtener el valor real de tu dinero.',
    metaTitle: 'Blog — Consejos de conversión de divisas y tipos de cambio | Multi Converter',
    metaDesc: 'Guías sobre conversión de divisas, tipos de cambio y cómo sacar el máximo valor a tu dinero, del equipo de Multi Converter.',
    allPosts: 'Todos los artículos', keepReading: 'Seguir leyendo', minRead: 'min de lectura',
  },
  fr: {
    indexTitle: 'Le blog Multi Converter',
    indexIntro: 'Des guides clairs sur la conversion de devises, les taux de change et comment obtenir la vraie valeur de votre argent.',
    metaTitle: 'Blog — Conseils de conversion de devises et taux de change | Multi Converter',
    metaDesc: 'Des guides sur la conversion de devises, les taux de change et comment tirer le meilleur de votre argent, par l’équipe de Multi Converter.',
    allPosts: 'Tous les articles', keepReading: 'À lire ensuite', minRead: 'min de lecture',
  },
  de: {
    indexTitle: 'Der Multi-Converter-Blog',
    indexIntro: 'Verständliche Ratgeber zu Währungsumrechnung, Wechselkursen und dem wahren Wert deines Geldes.',
    metaTitle: 'Blog — Tipps zur Währungsumrechnung & Wechselkurse | Multi Converter',
    metaDesc: 'Ratgeber zu Währungsumrechnung, Wechselkursen und wie du den besten Wert für dein Geld bekommst – vom Team hinter Multi Converter.',
    allPosts: 'Alle Beiträge', keepReading: 'Weiterlesen', minRead: 'Min. Lesezeit',
  },
  pt: {
    indexTitle: 'O blog do Multi Converter',
    indexIntro: 'Guias simples sobre conversão de moedas, taxas de câmbio e como obter o valor real do seu dinheiro.',
    metaTitle: 'Blog — Dicas de conversão de moedas e taxas de câmbio | Multi Converter',
    metaDesc: 'Guias sobre conversão de moedas, taxas de câmbio e como aproveitar melhor o seu dinheiro, da equipe do Multi Converter.',
    allPosts: 'Todos os artigos', keepReading: 'Continue lendo', minRead: 'min de leitura',
  },
}

export const LOCALIZED: Record<string, Record<string, LocalizedPost>> = {
  es: {
    'how-to-convert-currency': {
      title: 'Cómo convertir divisas: una guía sencilla para 2026',
      description: 'Aprende a convertir divisas de forma fácil. Entiende los tipos de cambio, la tasa media de mercado y cómo convertir cualquier cantidad al instante con un conversor de divisas gratis.',
      excerpt: 'Los tipos de cambio pueden resultar confusos. Esta es una guía clara para convertir divisas correctamente y evitar los costes ocultos que casi todos pasan por alto.',
      body: [
        { t: 'p', text: 'Tanto si viajas, compras por internet o envías dinero al extranjero, convertir divisas es algo que casi todos hacemos. Pero los tipos de cambio se mueven constantemente, y la cifra que te da tu banco rara vez es la tasa “real”. Esta guía explica cómo funciona de verdad la conversión de divisas y cómo convertir cualquier cantidad en segundos.' },
        { t: 'h2', text: '¿Qué es la conversión de divisas?' },
        { t: 'p', text: 'Convertir divisas es simplemente expresar el valor de una moneda en términos de otra. Si 1 dólar estadounidense equivale a 0,92 euros, convertir 100 USD te da 92 EUR. El número que une ambas monedas es el tipo de cambio.' },
        { t: 'h2', text: 'Entender los tipos de cambio' },
        { t: 'p', text: 'Los tipos de cambio cambian a lo largo del día según la oferta y la demanda en los mercados globales. La referencia más justa es la tasa media de mercado: el punto medio entre el precio de compra y de venta al que operan los bancos. Un buen conversor te muestra esta tasa media para que siempre sepas el valor real.' },
        { t: 'rate', base: 'USD', quote: 'EUR' },
        { t: 'h2', text: 'Cómo convertir divisas, paso a paso' },
        { t: 'ul', items: [
          'Elige la moneda que tienes (tu moneda base).',
          'Elige la moneda a la que quieres convertir.',
          'Introduce la cantidad: el valor convertido se actualiza al instante.',
          'Consulta la tasa media de mercado para conocer el valor real antes de pagar.',
        ] },
        { t: 'h2', text: 'Cuidado con las comisiones ocultas' },
        { t: 'p', text: 'Los bancos, los quioscos de cambio del aeropuerto y muchas apps añaden un margen sobre la tasa media, más comisiones fijas. Ese diferencial puede costarte un 3–6% sin que lo notes. Compara siempre la tasa que te ofrecen con la tasa media de mercado: si la diferencia es grande, estás pagando de más.' },
        { t: 'cta', text: 'Convierte cualquier divisa con tasas medias de mercado en vivo' },
      ],
    },
    'best-free-currency-converter-apps': {
      title: 'Las mejores apps gratuitas de conversión de divisas en 2026',
      description: '¿Buscas el mejor conversor de divisas gratis? Esto es lo que de verdad importa: tasas en vivo, conversión de varias monedas, modo sin conexión y sin anuncios ni rastreo.',
      excerpt: 'No todos los conversores de divisas son iguales. Esto es lo que debes buscar en un conversor gratis, y por qué gana lo simple, privado y rápido.',
      body: [
        { t: 'p', text: 'Busca un conversor de divisas y encontrarás cientos de apps, casi todas llenas de anuncios, registros y rastreadores. Un buen conversor debería hacer una cosa de maravilla: decirte el valor real de tu dinero, al instante. Esto es lo que debes buscar.' },
        { t: 'h2', text: '¿Qué hace bueno a un conversor de divisas?' },
        { t: 'ul', items: [
          'Tasas en vivo actualizadas a diario desde una fuente fiable.',
          'Tasa media de mercado, no una tasa bancaria con margen.',
          'Varias monedas a la vez, para comparar de un vistazo.',
          'Una calculadora integrada para hacer cuentas rápidas mientras conviertes.',
          'Funciona sin conexión usando tasas guardadas.',
          'Sin anuncios, sin registro y sin rastreo.',
        ] },
        { t: 'h2', text: 'Por qué creamos Multi Converter' },
        { t: 'p', text: 'Multi Converter muestra más de 100 monedas actualizándose juntas mientras escribes, incluye una calculadora integrada y no guarda nada sobre ti. Es gratis para siempre, sin anuncios y sin cuenta: solo ábrelo y convierte.' },
        { t: 'rate', base: 'USD', quote: 'GBP' },
        { t: 'cta', text: 'Prueba el conversor de divisas gratis' },
      ],
    },
    'what-is-mid-market-exchange-rate': {
      title: '¿Qué es la tasa media de mercado? (Y por qué importa)',
      description: 'La tasa media de mercado es el tipo de cambio real y más justo. Aprende qué es, por qué los bancos cobran más y cómo usarla para no pagar de más al convertir.',
      excerpt: 'Seguro que has visto el término “tasa media de mercado”. Es el tipo de cambio real, y conocerlo puede ahorrarte dinero en cada conversión.',
      body: [
        { t: 'p', text: 'Cuando lees que “1 USD = 0,92 EUR”, esa cifra suele ser la tasa media de mercado. Es el número más útil de la conversión de divisas, y sin embargo casi nadie lo paga realmente. Esto es lo que significa.' },
        { t: 'h2', text: 'La tasa media de mercado, definida' },
        { t: 'p', text: 'En cada momento, las monedas se compran y se venden a precios ligeramente distintos: el de compra (bid) y el de venta (ask). La tasa media de mercado es el punto medio entre ambos. Es la tasa que usan los bancos para operar entre sí, por eso se considera el tipo de cambio real y justo.' },
        { t: 'rate', base: 'EUR', quote: 'USD' },
        { t: 'h2', text: 'Por qué tu banco cobra más' },
        { t: 'p', text: 'Los bancos y las apps de dinero parten de la tasa media de mercado y añaden un margen: su beneficio. También pueden añadir comisiones fijas. Por eso la cantidad que recibes casi siempre es menor que la que sugiere un cálculo con la tasa media.' },
        { t: 'h2', text: 'Cómo usarla a tu favor' },
        { t: 'ul', items: [
          'Consulta siempre la tasa media de mercado antes de cambiar dinero.',
          'Compárala con la tasa que te ofrece tu banco o app.',
          'Si la diferencia supera el 1–2%, busca una opción más barata.',
        ] },
        { t: 'cta', text: 'Mira las tasas medias de mercado en vivo para cualquier par' },
      ],
    },
    'convert-usd-to-inr': {
      title: 'USD a INR: cómo convertir dólares estadounidenses a rupias indias',
      description: 'Convierte USD a INR con tipos de cambio en vivo. Mira la tasa de hoy del dólar estadounidense a la rupia india y aprende a convertir dólares a rupias al instante y gratis.',
      excerpt: '¿Conviertes dólares estadounidenses a rupias indias? Aquí tienes la tasa USD a INR en vivo y cómo convertir cualquier cantidad.',
      body: [
        { t: 'p', text: 'USD a INR —el dólar estadounidense frente a la rupia india— es una de las conversiones de divisas más buscadas del mundo. Desde remesas y trabajo freelance hasta viajes y compras online, millones de personas necesitan convertir dólares a rupias cada día. Aquí tienes la tasa en vivo y cómo hacerlo.' },
        { t: 'rate', base: 'USD', quote: 'INR' },
        { t: 'h2', text: '¿Qué mueve la tasa USD/INR?' },
        { t: 'p', text: 'La rupia india flota frente al dólar, así que la tasa USD a INR cambia a diario según los tipos de interés, la inflación, el precio del petróleo y la demanda de dólares. Como se mueve, conviene consultar una tasa media de mercado en vivo antes de convertir o enviar dinero.' },
        { t: 'h2', text: 'Cómo convertir dólares a rupias' },
        { t: 'ul', items: [
          'Introduce la cantidad en dólares estadounidenses (USD).',
          'Lee al instante el valor convertido en rupias indias (INR) a la tasa en vivo.',
          'Compara la tasa media de mercado con la que ofrece tu banco o servicio de transferencia: la diferencia es tu coste real.',
        ] },
        { t: 'p', text: 'Sobre todo en remesas, incluso una diferencia del 1–2% en la tasa se acumula. Compara siempre primero con la tasa media de mercado.' },
        { t: 'cta', text: 'Convierte USD a INR ahora' },
      ],
    },
    'eur-to-usd': {
      title: 'EUR a USD: convierte euros a dólares estadounidenses',
      description: 'Convierte EUR a USD con tipos de cambio en vivo. Mira la tasa de hoy del euro al dólar estadounidense y aprende a convertir euros a dólares al instante y gratis.',
      excerpt: '¿Conviertes euros a dólares estadounidenses? Aquí tienes la tasa EUR a USD en vivo y cómo convertir cualquier cantidad en segundos.',
      body: [
        { t: 'p', text: 'EUR/USD —el euro frente al dólar estadounidense— es el par de divisas más negociado del mundo. Si compras en tiendas de EE. UU., cobras en dólares o viajas entre Europa y Estados Unidos, necesitarás convertir euros a dólares. Aquí tienes la tasa en vivo y cómo hacerlo.' },
        { t: 'rate', base: 'EUR', quote: 'USD' },
        { t: 'h2', text: 'Sobre el tipo de cambio EUR/USD' },
        { t: 'p', text: 'A diferencia de una moneda con paridad fija, EUR/USD flota libremente, así que la tasa se mueve a lo largo del día según los tipos de interés, la inflación y la demanda global. Por eso conviene consultar una tasa media de mercado en vivo antes de convertir o cambiar dinero.' },
        { t: 'h2', text: 'Cómo convertir euros a dólares' },
        { t: 'ul', items: [
          'Introduce la cantidad en euros (EUR).',
          'Lee al instante el valor convertido en dólares estadounidenses (USD).',
          'Compara la tasa media de mercado con la que ofrece tu banco o tarjeta.',
        ] },
        { t: 'cta', text: 'Convierte EUR a USD ahora' },
      ],
    },
    'best-exchange-rate-travel': {
      title: 'Cómo conseguir el mejor tipo de cambio al viajar',
      description: '¿Viajas al extranjero? Aprende a conseguir el mejor tipo de cambio, evitar los quioscos del aeropuerto y las comisiones ocultas de las tarjetas, y usar la tasa media de mercado para ahorrar.',
      excerpt: 'Los quioscos del aeropuerto y las comisiones de tarjeta se comen tu dinero de viaje sin que lo notes. Así consigues el mejor tipo de cambio en el extranjero.',
      body: [
        { t: 'p', text: 'Cambiar dinero mientras viajas es donde más se pierde por malas tasas y comisiones ocultas. Unos pocos hábitos sencillos pueden ahorrarte dinero de verdad en cada viaje. Así consigues el mejor tipo de cambio en el extranjero.' },
        { t: 'h2', text: 'Conoce primero la tasa media de mercado' },
        { t: 'p', text: 'Antes de cambiar nada, consulta la tasa media de mercado: la tasa real y justa. Es tu referencia. Si una casa de cambio o una tarjeta te ofrece algo mucho peor, sabrás que debes rechazarlo.' },
        { t: 'rate', base: 'USD', quote: 'EUR' },
        { t: 'h2', text: 'Evita las peores opciones' },
        { t: 'ul', items: [
          'Quioscos de cambio en aeropuertos y hoteles: ofrecen algunas de las peores tasas que existen.',
          '“Conversión dinámica de divisa”: cuando el datáfono te ofrece cobrar en tu moneda, elige siempre la moneda local.',
          'Sacar cantidades pequeñas muchas veces, que acumula comisiones fijas de cajero.',
        ] },
        { t: 'h2', text: 'Formas inteligentes de pagar en el extranjero' },
        { t: 'ul', items: [
          'Usa una tarjeta que aplique la tasa media de mercado sin comisión por transacción extranjera.',
          'Saca cantidades mayores con menos frecuencia para reducir las comisiones fijas.',
          'Comprueba siempre la cantidad convertida frente a la tasa media de mercado antes de confirmar.',
        ] },
        { t: 'cta', text: 'Consulta las tasas en vivo antes de viajar' },
      ],
    },
    'money-converter-guide': {
      title: 'Conversor de dinero: cómo convertir cualquier divisa del mundo',
      description: '¿Buscas un conversor de dinero universal? Aprende a convertir dinero entre dos divisas cualquiera al instante, gratis, con tasas en vivo, sin importar qué monedas uses.',
      excerpt: 'Un conversor de dinero universal debería manejar cualquier par de divisas, no solo las populares. Así se convierte dinero entre dos monedas cualquiera correctamente.',
      body: [
        { t: 'p', text: 'La mayoría de los "conversores de dinero" solo manejan bien un puñado de divisas importantes. Pero el dinero se mueve entre todo tipo de pares: baht tailandés a peso mexicano, naira nigeriano a yen japonés, lira turca a rand sudafricano. Un conversor de dinero verdaderamente universal debería manejar cualquier par al instante, con la misma precisión que USD/EUR.' },
        { t: 'h2', text: 'Qué hace que un conversor sea "universal"' },
        { t: 'ul', items: [
          'Soporte para más de 100 monedas, no solo las 10 más populares.',
          'Conversión directa entre dos divisas cualquiera, no solo hacia y desde USD.',
          'Tasas medias de mercado en vivo, actualizadas a diario, para cada par.',
          'Sin bloqueo regional, sin monedas menores ausentes.',
        ] },
        { t: 'rate', base: 'GBP', quote: 'JPY' },
        { t: 'h2', text: 'Cómo funciona realmente la conversión entre divisas' },
        { t: 'p', text: 'Detrás de escena, la mayoría de las tasas se calculan a través de una moneda de referencia común (normalmente el USD). Para convertir GBP a JPY, un conversor toma la tasa GBP→USD y la tasa USD→JPY y las combina; nunca ves este paso, solo ves GBP→JPY directamente. Multi Converter hace esto automáticamente para cada moneda de su lista, así que cualquier par que elijas simplemente funciona.' },
        { t: 'h2', text: 'Cómo convertir dinero entre dos divisas cualquiera' },
        { t: 'ul', items: [
          'Elige tu moneda de partida y la moneda que quieres.',
          'Escribe la cantidad: el valor convertido se actualiza al instante, sea cual sea el par.',
          'Consulta la tasa media de mercado como referencia justa antes de pagar o transferir.',
        ] },
        { t: 'cta', text: 'Convierte cualquier divisa del mundo, gratis' },
      ],
    },
    'what-affects-exchange-rate': {
      title: '¿Qué afecta al tipo de cambio? 5 factores que mueven las divisas',
      description: '¿Por qué cambian cada día los tipos de cambio? Aprende los 5 factores principales que mueven el precio de las divisas, desde los tipos de interés hasta la inflación.',
      excerpt: 'Los tipos de cambio nunca están quietos. Estos son los 5 factores reales que mueven la tasa entre dos divisas cualquiera, explicados de forma sencilla.',
      body: [
        { t: 'p', text: 'Abre un conversor de divisas en dos días distintos y la tasa casi nunca es exactamente igual. Los tipos de cambio se mueven constantemente: aquí tienes las cinco razones principales, explicadas sin tecnicismos.' },
        { t: 'rate', base: 'USD', quote: 'JPY' },
        { t: 'h2', text: '1. Los tipos de interés' },
        { t: 'p', text: 'Cuando el banco central de un país sube los tipos de interés, el dinero tiende a fluir hacia esa moneda buscando mejor rentabilidad, lo que empuja su valor al alza. Las decisiones de la Reserva Federal, el BCE o el Banco de Inglaterra son de los mayores motores individuales de los tipos de cambio.' },
        { t: 'h2', text: '2. La inflación' },
        { t: 'p', text: 'Una inflación más alta erosiona el poder adquisitivo de una moneda, lo que suele debilitarla frente a monedas con precios más estables. Las diferencias de inflación persistentes entre dos países son un motor a largo plazo de su tipo de cambio.' },
        { t: 'h2', text: '3. Los datos económicos y el crecimiento' },
        { t: 'p', text: 'Buenos datos de empleo, crecimiento del PIB o comercio suelen apoyar a una moneda, mientras que datos débiles la debilitan: los mercados reajustan constantemente el precio de las divisas según la última fotografía económica.' },
        { t: 'h2', text: '4. La estabilidad política y el apetito por el riesgo' },
        { t: 'p', text: 'Las monedas de países políticamente estables se consideran generalmente más seguras. Elecciones, cambios de política o tensión geopolítica pueden causar movimientos rápidos cuando los inversores mueven dinero hacia o desde el riesgo percibido.' },
        { t: 'h2', text: '5. Oferta, demanda y flujos comerciales' },
        { t: 'p', text: 'Un país que exporta mucho más de lo que importa suele ver una demanda constante de su moneda (los compradores la necesitan para pagar bienes), lo que puede sostener su valor con el tiempo, y al revés para las economías muy importadoras.' },
        { t: 'h2', text: 'Por qué esto te importa' },
        { t: 'p', text: 'No necesitas seguir los cinco factores, pero saber que las tasas se mueven por razones reales (no al azar) explica por qué la tasa de hoy puede ser distinta mañana, y por qué consultar una tasa en vivo antes de convertir o enviar dinero siempre gana a fiarse de un número antiguo de memoria.' },
        { t: 'cta', text: 'Consulta la tasa de conversión en vivo de hoy' },
      ],
    },
    'gbp-to-usd': {
      title: 'GBP a USD: convierte libras esterlinas a dólares estadounidenses',
      description: 'Convierte GBP a USD con tipos de cambio en vivo. Mira la tasa de hoy de la libra esterlina al dólar estadounidense y convierte libras a dólares gratis.',
      excerpt: '¿Conviertes libras esterlinas a dólares? Aquí tienes la tasa GBP a USD en vivo y cómo convertir cualquier cantidad en segundos.',
      body: [
        { t: 'p', text: 'GBP/USD —conocido en los mercados como “cable”— es uno de los pares de divisas más antiguos y negociados del mundo. Si compras en tiendas de EE. UU., cobras en dólares o vuelas entre Londres y Nueva York, aquí tienes la tasa libra-dólar en vivo y cómo convertirla.' },
        { t: 'rate', base: 'GBP', quote: 'USD' },
        { t: 'h2', text: '¿Qué mueve la tasa GBP/USD?' },
        { t: 'p', text: 'Tanto la libra como el dólar flotan libremente, así que la tasa se mueve durante el día con las decisiones de tipos del Banco de Inglaterra y la Reserva Federal, los datos de inflación y el sentimiento global. Por eso conviene consultar una tasa media de mercado en vivo antes de convertir.' },
        { t: 'h2', text: 'Cómo convertir libras a dólares' },
        { t: 'ul', items: [
          'Introduce la cantidad en libras esterlinas (GBP).',
          'Lee al instante el valor convertido en dólares (USD) a la tasa en vivo.',
          'Compara la tasa media de mercado con la que ofrece tu banco o tarjeta: la diferencia es tu coste real.',
        ] },
        { t: 'cta', text: 'Convierte GBP a USD ahora' },
      ],
    },
    'usd-to-php': {
      title: 'USD a PHP: convierte dólares estadounidenses a pesos filipinos',
      description: 'Convierte USD a PHP con tipos de cambio en vivo. Mira la tasa de hoy del dólar al peso filipino —clave para remesas— y convierte dólares a pesos gratis.',
      excerpt: '¿Envías dólares a Filipinas? Aquí tienes la tasa USD a PHP en vivo y cómo asegurarte un valor justo en cada transferencia.',
      body: [
        { t: 'p', text: 'USD a PHP es una de las conversiones más buscadas del mundo, impulsada por millones de trabajadores filipinos en el extranjero que envían dinero a casa. Ya sean remesas, ingresos freelance o viajes, aquí tienes la tasa dólar-peso en vivo y cómo proteger su valor.' },
        { t: 'rate', base: 'USD', quote: 'PHP' },
        { t: 'h2', text: 'Por qué la tasa importa tanto en las remesas' },
        { t: 'p', text: 'En las remesas, el tipo de cambio suele costar más que la comisión visible. Un servicio que ofrece una tasa solo un 2% por debajo de la media de mercado se queda en silencio con el 2% de todo lo que envías. En un año de envíos mensuales, eso es dinero real.' },
        { t: 'h2', text: 'Cómo obtener un valor justo en USD a PHP' },
        { t: 'ul', items: [
          'Consulta la tasa media USD/PHP en vivo antes de enviar: es tu referencia.',
          'Compara la tasa de tu servicio de remesas con ella, no solo la comisión.',
          'Convierte primero la cantidad exacta para saber cuántos pesos deberían llegar.',
        ] },
        { t: 'cta', text: 'Convierte USD a PHP ahora' },
      ],
    },
  },
  fr: {
    'how-to-convert-currency': {
      title: 'Comment convertir des devises : un guide simple pour 2026',
      description: 'Apprenez à convertir des devises facilement. Comprenez les taux de change, le taux interbancaire et comment convertir n’importe quel montant en un instant avec un convertisseur gratuit.',
      excerpt: 'Les taux de change peuvent sembler compliqués. Voici un guide clair pour convertir vos devises correctement et éviter les coûts cachés que la plupart des gens ignorent.',
      body: [
        { t: 'p', text: 'Que vous voyagiez, achetiez en ligne ou envoyiez de l’argent à l’étranger, convertir des devises est une chose que presque tout le monde fait. Mais les taux de change bougent sans cesse, et le chiffre donné par votre banque est rarement le taux « réel ». Ce guide explique comment fonctionne vraiment la conversion de devises et comment convertir n’importe quel montant en quelques secondes.' },
        { t: 'h2', text: 'Qu’est-ce que la conversion de devises ?' },
        { t: 'p', text: 'Convertir une devise, c’est simplement exprimer la valeur d’une monnaie dans une autre. Si 1 dollar américain vaut 0,92 euro, convertir 100 USD donne 92 EUR. Le nombre qui relie les deux monnaies s’appelle le taux de change.' },
        { t: 'h2', text: 'Comprendre les taux de change' },
        { t: 'p', text: 'Les taux de change évoluent tout au long de la journée selon l’offre et la demande sur les marchés mondiaux. La référence la plus juste est le taux interbancaire : le point médian entre le prix d’achat et de vente auquel les banques échangent. Un bon convertisseur affiche ce taux interbancaire pour que vous connaissiez toujours la vraie valeur.' },
        { t: 'rate', base: 'USD', quote: 'EUR' },
        { t: 'h2', text: 'Comment convertir une devise, étape par étape' },
        { t: 'ul', items: [
          'Choisissez la devise que vous possédez (votre devise de base).',
          'Choisissez la devise vers laquelle convertir.',
          'Saisissez le montant : la valeur convertie se met à jour instantanément.',
          'Vérifiez le taux interbancaire pour connaître la vraie valeur avant de payer.',
        ] },
        { t: 'h2', text: 'Attention aux frais cachés' },
        { t: 'p', text: 'Les banques, les bureaux de change d’aéroport et de nombreuses applis ajoutent une marge au taux interbancaire, plus des frais fixes. Cet écart peut vous coûter discrètement 3 à 6 %. Comparez toujours le taux proposé au taux interbancaire : si l’écart est grand, vous payez trop cher.' },
        { t: 'cta', text: 'Convertissez n’importe quelle devise au taux interbancaire en direct' },
      ],
    },
    'best-free-currency-converter-apps': {
      title: 'Les meilleures applis gratuites de conversion de devises en 2026',
      description: 'Vous cherchez le meilleur convertisseur de devises gratuit ? Voici ce qui compte vraiment : taux en direct, conversion multi-devises, mode hors ligne, sans publicité ni suivi.',
      excerpt: 'Tous les convertisseurs ne se valent pas. Voici ce qu’il faut rechercher dans un convertisseur gratuit, et pourquoi le simple, privé et rapide l’emporte.',
      body: [
        { t: 'p', text: 'Cherchez un convertisseur de devises et vous trouverez des centaines d’applis, la plupart bourrées de publicités, d’inscriptions et de traqueurs. Un bon convertisseur devrait faire une seule chose à la perfection : vous indiquer la vraie valeur de votre argent, instantanément. Voici ce qu’il faut rechercher.' },
        { t: 'h2', text: 'Qu’est-ce qui fait un bon convertisseur ?' },
        { t: 'ul', items: [
          'Des taux en direct mis à jour chaque jour depuis une source fiable.',
          'Le taux interbancaire, pas un taux bancaire avec marge.',
          'Plusieurs devises à la fois, pour comparer d’un coup d’œil.',
          'Une calculatrice intégrée pour les calculs rapides pendant la conversion.',
          'Fonctionne hors ligne grâce aux taux enregistrés.',
          'Sans publicité, sans inscription et sans suivi.',
        ] },
        { t: 'h2', text: 'Pourquoi nous avons créé Multi Converter' },
        { t: 'p', text: 'Multi Converter affiche plus de 100 devises qui se mettent à jour ensemble pendant que vous tapez, inclut une calculatrice intégrée et ne conserve rien sur vous. Il est gratuit pour toujours, sans publicité et sans compte : ouvrez-le et convertissez.' },
        { t: 'rate', base: 'USD', quote: 'GBP' },
        { t: 'cta', text: 'Essayez le convertisseur de devises gratuit' },
      ],
    },
    'what-is-mid-market-exchange-rate': {
      title: 'Qu’est-ce que le taux interbancaire ? (Et pourquoi il compte)',
      description: 'Le taux interbancaire est le taux de change réel et le plus juste. Découvrez ce que c’est, pourquoi les banques facturent plus et comment l’utiliser pour ne pas payer trop cher.',
      excerpt: 'Vous avez sûrement vu le terme « taux interbancaire ». C’est le taux de change réel, et le connaître peut vous faire économiser à chaque conversion.',
      body: [
        { t: 'p', text: 'Quand vous lisez « 1 USD = 0,92 EUR », ce chiffre correspond généralement au taux interbancaire. C’est le nombre le plus utile de la conversion de devises, et pourtant presque personne ne le paie réellement. Voici ce qu’il signifie.' },
        { t: 'h2', text: 'Le taux interbancaire, défini' },
        { t: 'p', text: 'À chaque instant, les devises s’achètent et se vendent à des prix légèrement différents : le cours acheteur (bid) et le cours vendeur (ask). Le taux interbancaire est le point médian entre les deux. C’est le taux que les banques utilisent entre elles, ce qui en fait le taux de change réel et juste.' },
        { t: 'rate', base: 'EUR', quote: 'USD' },
        { t: 'h2', text: 'Pourquoi votre banque facture plus' },
        { t: 'p', text: 'Les banques et les applis partent du taux interbancaire et ajoutent une marge : leur bénéfice. Elles peuvent aussi ajouter des frais fixes. C’est pourquoi le montant reçu est presque toujours inférieur à ce qu’un calcul au taux interbancaire laisse penser.' },
        { t: 'h2', text: 'Comment l’utiliser à votre avantage' },
        { t: 'ul', items: [
          'Vérifiez toujours le taux interbancaire avant de changer de l’argent.',
          'Comparez-le au taux proposé par votre banque ou votre appli.',
          'Si l’écart dépasse 1 à 2 %, cherchez une option moins chère.',
        ] },
        { t: 'cta', text: 'Voir les taux interbancaires en direct pour n’importe quelle paire' },
      ],
    },
    'convert-usd-to-inr': {
      title: 'USD vers INR : convertir des dollars américains en roupies indiennes',
      description: 'Convertissez USD en INR avec des taux en direct. Voyez le taux du jour du dollar américain vers la roupie indienne et convertissez des dollars en roupies en un instant, gratuitement.',
      excerpt: 'Vous convertissez des dollars américains en roupies indiennes ? Voici le taux USD vers INR en direct et comment convertir n’importe quel montant.',
      body: [
        { t: 'p', text: 'USD vers INR — le dollar américain face à la roupie indienne — est l’une des conversions les plus recherchées au monde. Des transferts d’argent au freelancing, en passant par les voyages et les achats en ligne, des millions de personnes ont besoin de convertir des dollars en roupies chaque jour. Voici le taux en direct et comment faire.' },
        { t: 'rate', base: 'USD', quote: 'INR' },
        { t: 'h2', text: 'Qu’est-ce qui fait bouger le taux USD/INR ?' },
        { t: 'p', text: 'La roupie indienne flotte face au dollar : le taux USD vers INR change donc chaque jour selon les taux d’intérêt, l’inflation, le prix du pétrole et la demande de dollars. Comme il bouge, mieux vaut vérifier un taux interbancaire en direct avant de convertir ou d’envoyer de l’argent.' },
        { t: 'h2', text: 'Comment convertir des dollars en roupies' },
        { t: 'ul', items: [
          'Saisissez le montant en dollars américains (USD).',
          'Lisez instantanément la valeur convertie en roupies indiennes (INR) au taux en direct.',
          'Comparez le taux interbancaire à celui de votre banque ou service de transfert : l’écart, c’est votre coût réel.',
        ] },
        { t: 'p', text: 'Pour les transferts d’argent surtout, même un écart de 1 à 2 % s’accumule. Comparez toujours d’abord au taux interbancaire.' },
        { t: 'cta', text: 'Convertir USD en INR maintenant' },
      ],
    },
    'eur-to-usd': {
      title: 'EUR vers USD : convertir des euros en dollars américains',
      description: 'Convertissez EUR en USD avec des taux en direct. Voyez le taux du jour de l’euro vers le dollar américain et convertissez des euros en dollars en un instant, gratuitement.',
      excerpt: 'Vous convertissez des euros en dollars américains ? Voici le taux EUR vers USD en direct et comment convertir n’importe quel montant en quelques secondes.',
      body: [
        { t: 'p', text: 'EUR/USD — l’euro face au dollar américain — est la paire de devises la plus échangée au monde. Si vous achetez dans des boutiques américaines, êtes payé en dollars ou voyagez entre l’Europe et les États-Unis, vous devrez convertir des euros en dollars. Voici le taux en direct et comment faire.' },
        { t: 'rate', base: 'EUR', quote: 'USD' },
        { t: 'h2', text: 'À propos du taux EUR/USD' },
        { t: 'p', text: 'Contrairement à une monnaie à parité fixe, l’EUR/USD flotte librement : le taux bouge donc au cours de la journée selon les taux d’intérêt, l’inflation et la demande mondiale. D’où l’intérêt de vérifier un taux interbancaire en direct avant de convertir ou de changer de l’argent.' },
        { t: 'h2', text: 'Comment convertir des euros en dollars' },
        { t: 'ul', items: [
          'Saisissez le montant en euros (EUR).',
          'Lisez instantanément la valeur convertie en dollars américains (USD).',
          'Comparez le taux interbancaire à celui de votre banque ou de votre carte.',
        ] },
        { t: 'cta', text: 'Convertir EUR en USD maintenant' },
      ],
    },
    'best-exchange-rate-travel': {
      title: 'Comment obtenir le meilleur taux de change en voyage',
      description: 'Vous voyagez à l’étranger ? Apprenez à obtenir le meilleur taux de change, à éviter les bureaux d’aéroport et les frais de carte cachés, et à utiliser le taux interbancaire pour économiser.',
      excerpt: 'Les bureaux d’aéroport et les frais de carte grignotent discrètement votre argent de voyage. Voici comment obtenir le meilleur taux de change à l’étranger.',
      body: [
        { t: 'p', text: 'Changer de l’argent en voyage, c’est là qu’on perd le plus à cause de mauvais taux et de frais cachés. Quelques habitudes simples peuvent vous faire vraiment économiser à chaque voyage. Voici comment obtenir le meilleur taux de change à l’étranger.' },
        { t: 'h2', text: 'Connaissez d’abord le taux interbancaire' },
        { t: 'p', text: 'Avant de changer quoi que ce soit, vérifiez le taux interbancaire : le taux réel et juste. C’est votre repère. Si un bureau de change ou une carte propose bien pire, vous saurez qu’il faut refuser.' },
        { t: 'rate', base: 'USD', quote: 'EUR' },
        { t: 'h2', text: 'Évitez les pires options' },
        { t: 'ul', items: [
          'Les bureaux de change d’aéroport et d’hôtel : ils proposent parmi les pires taux qui existent.',
          'La « conversion dynamique de devise » : quand un terminal propose de vous facturer dans votre monnaie, choisissez toujours la monnaie locale.',
          'Retirer de petites sommes à répétition, ce qui accumule les frais fixes de distributeur.',
        ] },
        { t: 'h2', text: 'Des moyens malins de payer à l’étranger' },
        { t: 'ul', items: [
          'Utilisez une carte qui applique le taux interbancaire sans frais de transaction à l’étranger.',
          'Retirez de plus grosses sommes moins souvent pour réduire les frais fixes.',
          'Vérifiez toujours le montant converti par rapport au taux interbancaire avant de confirmer.',
        ] },
        { t: 'cta', text: 'Vérifiez les taux en direct avant de partir' },
      ],
    },
    'money-converter-guide': {
      title: 'Convertisseur d’argent : comment convertir n’importe quelle devise au monde',
      description: 'Vous cherchez un convertisseur d’argent universel ? Apprenez à convertir de l’argent entre deux devises quelconques instantanément, gratuitement, avec des taux en direct.',
      excerpt: 'Un convertisseur d’argent universel devrait gérer n’importe quelle paire de devises, pas seulement les plus populaires. Voici comment convertir correctement entre deux devises quelconques.',
      body: [
        { t: 'p', text: 'La plupart des « convertisseurs d’argent » ne gèrent bien qu’une poignée de devises importantes. Mais l’argent circule entre toutes sortes de paires : baht thaïlandais vers peso mexicain, naira nigérian vers yen japonais, livre turque vers rand sud-africain. Un vrai convertisseur universel devrait gérer n’importe quelle paire instantanément, avec la même précision que l’EUR/USD.' },
        { t: 'h2', text: 'Ce qui rend un convertisseur « universel »' },
        { t: 'ul', items: [
          'Prise en charge de plus de 100 devises, pas seulement les 10 plus populaires.',
          'Conversion directe entre deux devises quelconques, pas seulement vers ou depuis l’USD.',
          'Des taux interbancaires en direct, mis à jour chaque jour, pour chaque paire.',
          'Aucun blocage régional, aucune devise mineure manquante.',
        ] },
        { t: 'rate', base: 'GBP', quote: 'JPY' },
        { t: 'h2', text: 'Comment fonctionne vraiment la conversion entre devises' },
        { t: 'p', text: 'En coulisses, la plupart des taux sont calculés via une devise de référence commune (généralement l’USD). Pour convertir GBP en JPY, un convertisseur prend le taux GBP→USD et le taux USD→JPY et les combine ; vous ne voyez jamais cette étape, seulement le résultat GBP→JPY. Multi Converter le fait automatiquement pour chaque devise de sa liste, donc n’importe quelle paire fonctionne simplement.' },
        { t: 'h2', text: 'Comment convertir de l’argent entre deux devises quelconques' },
        { t: 'ul', items: [
          'Choisissez votre devise de départ et celle que vous voulez.',
          'Saisissez le montant : la valeur convertie se met à jour instantanément, quelle que soit la paire.',
          'Vérifiez le taux interbancaire comme référence juste avant de payer ou de transférer.',
        ] },
        { t: 'cta', text: 'Convertissez n’importe quelle devise au monde, gratuitement' },
      ],
    },
    'what-affects-exchange-rate': {
      title: 'Qu’est-ce qui influence le taux de change ? 5 facteurs qui font bouger les devises',
      description: 'Pourquoi les taux de change changent-ils chaque jour ? Découvrez les 5 principaux facteurs qui font bouger le prix des devises, des taux d’intérêt à l’inflation.',
      excerpt: 'Les taux de change ne restent jamais immobiles. Voici les 5 vraies raisons qui font bouger le taux entre deux devises quelconques, expliquées simplement.',
      body: [
        { t: 'p', text: 'Ouvrez un convertisseur de devises deux jours différents et le taux n’est presque jamais exactement le même. Les taux de change bougent en permanence : voici les cinq plus grandes raisons, expliquées sans jargon.' },
        { t: 'rate', base: 'USD', quote: 'JPY' },
        { t: 'h2', text: '1. Les taux d’intérêt' },
        { t: 'p', text: 'Quand la banque centrale d’un pays relève ses taux d’intérêt, l’argent a tendance à affluer vers cette devise en quête de meilleurs rendements, poussant sa valeur à la hausse. Les décisions de la Fed, de la BCE ou de la Banque d’Angleterre sont parmi les plus gros moteurs individuels des taux de change.' },
        { t: 'h2', text: '2. L’inflation' },
        { t: 'p', text: 'Une inflation plus élevée érode le pouvoir d’achat d’une devise, ce qui l’affaiblit généralement face aux devises aux prix plus stables. Des écarts d’inflation persistants entre deux pays sont un moteur de long terme de leur taux de change.' },
        { t: 'h2', text: '3. Les données économiques et la croissance' },
        { t: 'p', text: 'De bons chiffres de l’emploi, de la croissance du PIB ou du commerce ont tendance à soutenir une devise, tandis que des données faibles la tirent vers le bas : les marchés réévaluent en permanence les devises selon la dernière photographie économique.' },
        { t: 'h2', text: '4. La stabilité politique et l’appétit pour le risque' },
        { t: 'p', text: 'Les devises de pays politiquement stables sont généralement perçues comme plus sûres. Élections, changements de politique ou tensions géopolitiques peuvent provoquer des mouvements rapides quand les investisseurs déplacent leur argent vers ou hors du risque perçu.' },
        { t: 'h2', text: '5. L’offre, la demande et les flux commerciaux' },
        { t: 'p', text: 'Un pays qui exporte bien plus qu’il n’importe voit généralement une demande constante pour sa devise (les acheteurs en ont besoin pour payer des biens), ce qui peut soutenir sa valeur dans le temps — et inversement pour les économies très importatrices.' },
        { t: 'h2', text: 'Pourquoi cela vous concerne' },
        { t: 'p', text: 'Pas besoin de suivre les cinq facteurs, mais savoir que les taux bougent pour de vraies raisons (pas au hasard) explique pourquoi le taux d’aujourd’hui peut différer de celui de demain, et pourquoi vérifier un taux en direct avant de convertir ou d’envoyer de l’argent l’emporte toujours sur un vieux chiffre gardé en mémoire.' },
        { t: 'cta', text: 'Vérifiez le taux de conversion en direct aujourd’hui' },
      ],
    },
    'gbp-to-usd': {
      title: 'GBP vers USD : convertir des livres sterling en dollars américains',
      description: 'Convertissez GBP en USD avec des taux en direct. Voyez le taux du jour de la livre sterling vers le dollar américain et convertissez gratuitement.',
      excerpt: 'Vous convertissez des livres sterling en dollars ? Voici le taux GBP vers USD en direct et comment convertir n’importe quel montant en quelques secondes.',
      body: [
        { t: 'p', text: 'GBP/USD — surnommé « cable » sur les marchés — est l’une des paires de devises les plus anciennes et les plus échangées au monde. Que vous achetiez dans des boutiques américaines, soyez payé en dollars ou voyagiez entre Londres et New York, voici le taux livre-dollar en direct et comment le convertir.' },
        { t: 'rate', base: 'GBP', quote: 'USD' },
        { t: 'h2', text: 'Qu’est-ce qui fait bouger le taux GBP/USD ?' },
        { t: 'p', text: 'La livre et le dollar flottent librement : le taux évolue donc au fil de la journée avec les décisions de la Banque d’Angleterre et de la Réserve fédérale, les données d’inflation et le sentiment de marché mondial. D’où l’intérêt de vérifier un taux interbancaire en direct avant de convertir.' },
        { t: 'h2', text: 'Comment convertir des livres en dollars' },
        { t: 'ul', items: [
          'Saisissez le montant en livres sterling (GBP).',
          'Lisez instantanément la valeur convertie en dollars (USD) au taux en direct.',
          'Comparez le taux interbancaire à celui de votre banque ou carte : l’écart est votre coût réel.',
        ] },
        { t: 'cta', text: 'Convertir GBP en USD maintenant' },
      ],
    },
    'usd-to-php': {
      title: 'USD vers PHP : convertir des dollars américains en pesos philippins',
      description: 'Convertissez USD en PHP avec des taux en direct. Voyez le taux du jour du dollar vers le peso philippin — essentiel pour les transferts — gratuitement.',
      excerpt: 'Vous envoyez des dollars aux Philippines ? Voici le taux USD vers PHP en direct et comment obtenir une juste valeur à chaque transfert.',
      body: [
        { t: 'p', text: 'USD vers PHP est l’une des conversions les plus recherchées au monde, portée par des millions de travailleurs philippins à l’étranger qui envoient de l’argent à leur famille. Transferts, revenus freelance ou voyage : voici le taux dollar-peso en direct et comment en protéger la valeur.' },
        { t: 'rate', base: 'USD', quote: 'PHP' },
        { t: 'h2', text: 'Pourquoi le taux compte autant pour les transferts' },
        { t: 'p', text: 'Sur un transfert d’argent, le taux de change coûte généralement plus cher que les frais visibles. Un service qui propose un taux à peine 2 % sous le taux interbancaire garde discrètement 2 % de tout ce que vous envoyez. Sur un an d’envois mensuels, c’est de l’argent réel.' },
        { t: 'h2', text: 'Comment obtenir une juste valeur sur USD vers PHP' },
        { t: 'ul', items: [
          'Vérifiez le taux interbancaire USD/PHP en direct avant d’envoyer : c’est votre repère.',
          'Comparez le taux de votre service de transfert à ce repère, pas seulement les frais.',
          'Convertissez d’abord le montant exact pour savoir combien de pesos doivent arriver.',
        ] },
        { t: 'cta', text: 'Convertir USD en PHP maintenant' },
      ],
    },
  },
  de: {
    'how-to-convert-currency': {
      title: 'Währungen umrechnen: ein einfacher Leitfaden für 2026',
      description: 'Lerne, Währungen einfach umzurechnen. Verstehe Wechselkurse, den Mittelkurs und wie du jeden Betrag sofort mit einem kostenlosen Währungsrechner umrechnest.',
      excerpt: 'Wechselkurse können verwirrend wirken. Hier ist ein klarer Leitfaden, um Währungen richtig umzurechnen und die versteckten Kosten zu vermeiden, die die meisten übersehen.',
      body: [
        { t: 'p', text: 'Ob auf Reisen, beim Online-Shopping oder beim Geldsenden ins Ausland – Währungen umrechnen tun fast alle. Doch Wechselkurse ändern sich ständig, und die Zahl deiner Bank ist selten der „echte“ Kurs. Dieser Leitfaden erklärt, wie Währungsumrechnung wirklich funktioniert und wie du jeden Betrag in Sekunden umrechnest.' },
        { t: 'h2', text: 'Was ist Währungsumrechnung?' },
        { t: 'p', text: 'Währungsumrechnung bedeutet einfach, den Wert einer Währung in einer anderen auszudrücken. Wenn 1 US-Dollar 0,92 Euro entspricht, ergeben 100 USD umgerechnet 92 EUR. Die Zahl, die beide Währungen verbindet, ist der Wechselkurs.' },
        { t: 'h2', text: 'Wechselkurse verstehen' },
        { t: 'p', text: 'Wechselkurse ändern sich im Tagesverlauf je nach Angebot und Nachfrage an den globalen Märkten. Der fairste Bezugspunkt ist der Mittelkurs – die Mitte zwischen An- und Verkaufspreis, zu dem Banken handeln. Ein guter Rechner zeigt dir diesen Mittelkurs, damit du immer den echten Wert kennst.' },
        { t: 'rate', base: 'USD', quote: 'EUR' },
        { t: 'h2', text: 'Währungen umrechnen, Schritt für Schritt' },
        { t: 'ul', items: [
          'Wähle die Währung, die du hast (deine Basiswährung).',
          'Wähle die Währung, in die du umrechnen möchtest.',
          'Gib den Betrag ein – der umgerechnete Wert aktualisiert sich sofort.',
          'Prüfe den Mittelkurs, um vor dem Bezahlen den echten Wert zu kennen.',
        ] },
        { t: 'h2', text: 'Vorsicht vor versteckten Gebühren' },
        { t: 'p', text: 'Banken, Wechselstuben am Flughafen und viele Apps schlagen eine Marge auf den Mittelkurs auf, plus feste Gebühren. Dieser Aufschlag kann dich unbemerkt 3–6 % kosten. Vergleiche den angebotenen Kurs immer mit dem Mittelkurs: Ist der Unterschied groß, zahlst du zu viel.' },
        { t: 'cta', text: 'Rechne jede Währung zum Live-Mittelkurs um' },
      ],
    },
    'best-free-currency-converter-apps': {
      title: 'Die besten kostenlosen Währungsrechner-Apps 2026',
      description: 'Auf der Suche nach dem besten kostenlosen Währungsrechner? Darauf kommt es wirklich an: Live-Kurse, Umrechnung mehrerer Währungen, Offline-Modus, ohne Werbung und Tracking.',
      excerpt: 'Nicht alle Währungsrechner sind gleich. Darauf solltest du bei einem kostenlosen Rechner achten – und warum einfach, privat und schnell gewinnt.',
      body: [
        { t: 'p', text: 'Suche nach einem Währungsrechner und du findest Hunderte Apps – die meisten voll mit Werbung, Anmeldungen und Trackern. Ein guter Rechner sollte eine Sache perfekt machen: dir sofort den echten Wert deines Geldes nennen. Darauf solltest du achten.' },
        { t: 'h2', text: 'Was macht einen guten Währungsrechner aus?' },
        { t: 'ul', items: [
          'Live-Kurse, täglich aus einer vertrauenswürdigen Quelle aktualisiert.',
          'Mittelkurs statt aufgeschlagenem Bankkurs.',
          'Mehrere Währungen gleichzeitig, für den Vergleich auf einen Blick.',
          'Ein integrierter Rechner für schnelle Berechnungen beim Umrechnen.',
          'Funktioniert offline mit gespeicherten Kursen.',
          'Ohne Werbung, ohne Anmeldung und ohne Tracking.',
        ] },
        { t: 'h2', text: 'Warum wir Multi Converter entwickelt haben' },
        { t: 'p', text: 'Multi Converter zeigt über 100 Währungen, die sich beim Tippen gemeinsam aktualisieren, hat einen integrierten Rechner und speichert nichts über dich. Es ist für immer kostenlos, ohne Werbung und ohne Konto – einfach öffnen und umrechnen.' },
        { t: 'rate', base: 'USD', quote: 'GBP' },
        { t: 'cta', text: 'Probiere den kostenlosen Währungsrechner' },
      ],
    },
    'what-is-mid-market-exchange-rate': {
      title: 'Was ist der Mittelkurs? (Und warum er wichtig ist)',
      description: 'Der Mittelkurs ist der echte, fairste Wechselkurs. Erfahre, was er ist, warum Banken mehr verlangen und wie du ihn nutzt, um beim Umrechnen nicht zu viel zu zahlen.',
      excerpt: 'Du hast den Begriff „Mittelkurs“ sicher schon gesehen. Er ist der echte Wechselkurs – und ihn zu kennen kann bei jeder Umrechnung Geld sparen.',
      body: [
        { t: 'p', text: 'Wenn du liest „1 USD = 0,92 EUR“, ist das meist der Mittelkurs. Er ist die nützlichste Zahl der Währungsumrechnung – und doch zahlt ihn fast niemand wirklich. Das steckt dahinter.' },
        { t: 'h2', text: 'Der Mittelkurs, definiert' },
        { t: 'p', text: 'In jedem Moment werden Währungen zu leicht unterschiedlichen Preisen gehandelt: dem Geldkurs (bid) und dem Briefkurs (ask). Der Mittelkurs ist die Mitte zwischen beiden. Es ist der Kurs, zu dem Banken untereinander handeln – deshalb gilt er als der echte, faire Wechselkurs.' },
        { t: 'rate', base: 'EUR', quote: 'USD' },
        { t: 'h2', text: 'Warum deine Bank mehr verlangt' },
        { t: 'p', text: 'Banken und Geld-Apps starten beim Mittelkurs und schlagen eine Marge auf – ihren Gewinn. Dazu können feste Gebühren kommen. Deshalb ist der Betrag, den du erhältst, fast immer geringer als eine Rechnung zum Mittelkurs vermuten lässt.' },
        { t: 'h2', text: 'So nutzt du ihn zu deinem Vorteil' },
        { t: 'ul', items: [
          'Prüfe vor jedem Geldwechsel den Mittelkurs.',
          'Vergleiche ihn mit dem Kurs deiner Bank oder App.',
          'Liegt der Unterschied über 1–2 %, suche eine günstigere Option.',
        ] },
        { t: 'cta', text: 'Live-Mittelkurse für jedes Paar ansehen' },
      ],
    },
    'convert-usd-to-inr': {
      title: 'USD in INR: US-Dollar in Indische Rupie umrechnen',
      description: 'Rechne USD in INR mit Live-Kursen um. Sieh den heutigen Kurs vom US-Dollar zur Indischen Rupie und rechne Dollar sofort und kostenlos in Rupien um.',
      excerpt: 'Du rechnest US-Dollar in Indische Rupien um? Hier ist der Live-Kurs USD zu INR und wie du jeden Betrag umrechnest.',
      body: [
        { t: 'p', text: 'USD zu INR – der US-Dollar gegen die Indische Rupie – ist eine der weltweit meistgesuchten Umrechnungen. Von Überweisungen und Freelancing bis zu Reisen und Online-Shopping müssen täglich Millionen Menschen Dollar in Rupien umrechnen. Hier ist der Live-Kurs und wie es geht.' },
        { t: 'rate', base: 'USD', quote: 'INR' },
        { t: 'h2', text: 'Was bewegt den USD/INR-Kurs?' },
        { t: 'p', text: 'Die Indische Rupie schwankt frei gegenüber dem Dollar, daher ändert sich der USD-zu-INR-Kurs täglich – je nach Zinsen, Inflation, Ölpreis und Nachfrage nach Dollar. Da er sich bewegt, lohnt sich ein Blick auf einen Live-Mittelkurs, bevor du umrechnest oder Geld sendest.' },
        { t: 'h2', text: 'So rechnest du Dollar in Rupien um' },
        { t: 'ul', items: [
          'Gib den Betrag in US-Dollar (USD) ein.',
          'Lies sofort den umgerechneten Wert in Indischen Rupien (INR) zum Live-Kurs.',
          'Vergleiche den Mittelkurs mit dem deiner Bank oder deines Transferdienstes – die Differenz sind deine echten Kosten.',
        ] },
        { t: 'p', text: 'Gerade bei Überweisungen summiert sich schon ein Unterschied von 1–2 %. Vergleiche immer zuerst mit dem Mittelkurs.' },
        { t: 'cta', text: 'Jetzt USD in INR umrechnen' },
      ],
    },
    'eur-to-usd': {
      title: 'EUR in USD: Euro in US-Dollar umrechnen',
      description: 'Rechne EUR in USD mit Live-Kursen um. Sieh den heutigen Kurs vom Euro zum US-Dollar und rechne Euro sofort und kostenlos in Dollar um.',
      excerpt: 'Du rechnest Euro in US-Dollar um? Hier ist der Live-Kurs EUR zu USD und wie du jeden Betrag in Sekunden umrechnest.',
      body: [
        { t: 'p', text: 'EUR/USD – der Euro gegen den US-Dollar – ist das meistgehandelte Währungspaar der Welt. Wenn du in US-Shops einkaufst, in Dollar bezahlt wirst oder zwischen Europa und den USA reist, musst du Euro in Dollar umrechnen. Hier ist der Live-Kurs und wie es geht.' },
        { t: 'rate', base: 'EUR', quote: 'USD' },
        { t: 'h2', text: 'Über das Paar EUR/USD' },
        { t: 'p', text: 'Anders als eine fest gebundene Währung schwankt EUR/USD frei, daher bewegt sich der Kurs im Tagesverlauf – je nach Zinsen, Inflation und globaler Nachfrage. Deshalb lohnt ein Live-Mittelkurs, bevor du umrechnest oder Geld wechselst.' },
        { t: 'h2', text: 'So rechnest du Euro in Dollar um' },
        { t: 'ul', items: [
          'Gib den Betrag in Euro (EUR) ein.',
          'Lies sofort den umgerechneten Wert in US-Dollar (USD).',
          'Vergleiche den Mittelkurs mit dem deiner Bank oder Karte.',
        ] },
        { t: 'cta', text: 'Jetzt EUR in USD umrechnen' },
      ],
    },
    'best-exchange-rate-travel': {
      title: 'So bekommst du auf Reisen den besten Wechselkurs',
      description: 'Du reist ins Ausland? Lerne, wie du den besten Wechselkurs bekommst, Flughafen-Wechselstuben und versteckte Kartengebühren vermeidest und mit dem Mittelkurs sparst.',
      excerpt: 'Flughafen-Wechselstuben und Kartengebühren fressen unbemerkt dein Reisebudget. So bekommst du im Ausland den besten Wechselkurs.',
      body: [
        { t: 'p', text: 'Geld wechseln auf Reisen ist der Punkt, an dem man durch schlechte Kurse und versteckte Gebühren am meisten verliert. Ein paar einfache Gewohnheiten sparen bei jeder Reise echtes Geld. So bekommst du im Ausland den besten Wechselkurs.' },
        { t: 'h2', text: 'Kenne zuerst den Mittelkurs' },
        { t: 'p', text: 'Bevor du etwas wechselst, prüfe den Mittelkurs – den echten, fairen Kurs. Er ist dein Maßstab. Bietet eine Wechselstube oder Karte etwas deutlich Schlechteres, weißt du, dass du ablehnen solltest.' },
        { t: 'rate', base: 'USD', quote: 'EUR' },
        { t: 'h2', text: 'Vermeide die schlechtesten Optionen' },
        { t: 'ul', items: [
          'Wechselstuben an Flughäfen und in Hotels: Sie bieten einige der schlechtesten Kurse überhaupt.',
          '„Dynamische Währungsumrechnung“: Bietet ein Kartenterminal an, in deiner Heimatwährung abzurechnen, wähle immer die lokale Währung.',
          'Häufig kleine Beträge abheben, was feste Automatengebühren aufsummiert.',
        ] },
        { t: 'h2', text: 'Clever im Ausland bezahlen' },
        { t: 'ul', items: [
          'Nutze eine Karte, die den Mittelkurs ohne Auslandsgebühr anwendet.',
          'Hebe größere Beträge seltener ab, um feste Gebühren zu senken.',
          'Prüfe vor dem Bestätigen immer den umgerechneten Betrag gegen den Mittelkurs.',
        ] },
        { t: 'cta', text: 'Prüfe Live-Kurse, bevor du reist' },
      ],
    },
    'money-converter-guide': {
      title: 'Geld umrechnen: So rechnest du jede Währung der Welt um',
      description: 'Suchst du einen universellen Geld-Umrechner? Erfahre, wie du Geld zwischen zwei beliebigen Währungen sofort und kostenlos mit Live-Kursen umrechnest.',
      excerpt: 'Ein universeller Geld-Umrechner sollte jedes Währungspaar beherrschen, nicht nur die beliebten. So rechnest du Geld korrekt zwischen zwei beliebigen Währungen um.',
      body: [
        { t: 'p', text: 'Die meisten „Geld-Umrechner“ beherrschen nur eine Handvoll wichtiger Währungen gut. Aber Geld bewegt sich zwischen allen möglichen Paaren – thailändischer Baht zu mexikanischem Peso, nigerianischer Naira zu japanischem Yen, türkische Lira zu südafrikanischem Rand. Ein wirklich universeller Umrechner sollte jedes Paar sofort und mit derselben Genauigkeit wie EUR/USD beherrschen.' },
        { t: 'h2', text: 'Was einen Umrechner „universell“ macht' },
        { t: 'ul', items: [
          'Unterstützung für über 100 Währungen, nicht nur die 10 beliebtesten.',
          'Direkte Umrechnung zwischen zwei beliebigen Währungen, nicht nur zu und von USD.',
          'Live-Mittelkurse, täglich aktualisiert, für jedes Paar.',
          'Keine Regionssperre, keine fehlenden kleineren Währungen.',
        ] },
        { t: 'rate', base: 'GBP', quote: 'JPY' },
        { t: 'h2', text: 'Wie die Umrechnung zwischen Währungen wirklich funktioniert' },
        { t: 'p', text: 'Im Hintergrund werden die meisten Kurse über eine gemeinsame Referenzwährung (meist USD) berechnet. Um GBP in JPY umzurechnen, nimmt ein Rechner den Kurs GBP→USD und USD→JPY und kombiniert sie – du siehst diesen Schritt nie, nur direkt GBP→JPY. Multi Converter macht das automatisch für jede Währung in seiner Liste, sodass jedes gewählte Paar einfach funktioniert.' },
        { t: 'h2', text: 'So rechnest du Geld zwischen zwei beliebigen Währungen um' },
        { t: 'ul', items: [
          'Wähle deine Ausgangswährung und die gewünschte Währung.',
          'Gib den Betrag ein – der umgerechnete Wert aktualisiert sich sofort, egal welches Paar.',
          'Prüfe den Mittelkurs als fairen Maßstab, bevor du bezahlst oder überweist.',
        ] },
        { t: 'cta', text: 'Rechne jede Währung der Welt kostenlos um' },
      ],
    },
    'what-affects-exchange-rate': {
      title: 'Was beeinflusst den Wechselkurs? 5 Faktoren, die Währungen bewegen',
      description: 'Warum ändern sich Wechselkurse jeden Tag? Erfahre die 5 wichtigsten Faktoren, die Währungspreise bewegen – von Zinsen bis Inflation.',
      excerpt: 'Wechselkurse stehen nie still. Hier sind die 5 echten Gründe, warum sich der Kurs zwischen zwei beliebigen Währungen bewegt, einfach erklärt.',
      body: [
        { t: 'p', text: 'Öffne an zwei verschiedenen Tagen einen Währungsrechner und der Kurs ist fast nie exakt gleich. Wechselkurse bewegen sich ständig – hier sind die fünf größten Gründe, ohne Fachjargon erklärt.' },
        { t: 'rate', base: 'USD', quote: 'JPY' },
        { t: 'h2', text: '1. Zinsen' },
        { t: 'p', text: 'Wenn die Zentralbank eines Landes die Zinsen erhöht, fließt Geld tendenziell in diese Währung auf der Suche nach besserer Rendite, was ihren Wert steigen lässt. Zinsentscheidungen der US-Notenbank Fed, der EZB oder der Bank of England gehören zu den größten einzelnen Treibern von Wechselkursen.' },
        { t: 'h2', text: '2. Inflation' },
        { t: 'p', text: 'Höhere Inflation untergräbt die Kaufkraft einer Währung, was sie meist gegenüber Währungen mit stabileren Preisen schwächt. Anhaltende Inflationsunterschiede zwischen zwei Ländern sind ein langfristiger Treiber ihres Wechselkurses.' },
        { t: 'h2', text: '3. Wirtschaftsdaten und Wachstum' },
        { t: 'p', text: 'Starke Beschäftigungszahlen, BIP-Wachstum oder Handelsdaten stützen tendenziell eine Währung, während schwache Daten sie belasten – die Märkte bewerten Währungen ständig anhand der aktuellen Wirtschaftslage neu.' },
        { t: 'h2', text: '4. Politische Stabilität und Risikostimmung' },
        { t: 'p', text: 'Währungen politisch stabiler Länder gelten allgemein als sicherer. Wahlen, Politikwechsel oder geopolitische Spannungen können zu schnellen Ausschlägen führen, wenn Anleger Geld in Richtung oder weg von wahrgenommenem Risiko bewegen.' },
        { t: 'h2', text: '5. Angebot, Nachfrage und Handelsströme' },
        { t: 'p', text: 'Ein Land, das weit mehr exportiert als importiert, sieht meist eine stetige Nachfrage nach seiner Währung (Käufer brauchen sie, um Waren zu bezahlen), was ihren Wert über die Zeit stützen kann – und umgekehrt für importlastige Volkswirtschaften.' },
        { t: 'h2', text: 'Warum das für dich wichtig ist' },
        { t: 'p', text: 'Du musst nicht alle fünf Faktoren verfolgen – aber zu wissen, dass sich Kurse aus echten Gründen bewegen (nicht zufällig), erklärt, warum der heutige Kurs morgen anders sein kann, und warum ein Blick auf den Live-Kurs vor dem Umrechnen oder Überweisen immer besser ist als sich auf eine alte Zahl aus dem Gedächtnis zu verlassen.' },
        { t: 'cta', text: 'Prüfe den heutigen Live-Umrechnungskurs' },
      ],
    },
    'gbp-to-usd': {
      title: 'GBP in USD: Britische Pfund in US-Dollar umrechnen',
      description: 'Rechne GBP in USD mit Live-Kursen um. Sieh den heutigen Kurs vom britischen Pfund zum US-Dollar und rechne Pfund kostenlos in Dollar um.',
      excerpt: 'Du rechnest britische Pfund in US-Dollar um? Hier ist der Live-Kurs GBP zu USD und wie du jeden Betrag in Sekunden umrechnest.',
      body: [
        { t: 'p', text: 'GBP/USD — an den Märkten als „Cable“ bekannt — ist eines der ältesten und meistgehandelten Währungspaare der Welt. Ob du in US-Shops einkaufst, in Dollar bezahlt wirst oder zwischen London und New York fliegst: Hier ist der Live-Kurs Pfund–Dollar und wie du ihn umrechnest.' },
        { t: 'rate', base: 'GBP', quote: 'USD' },
        { t: 'h2', text: 'Was bewegt den GBP/USD-Kurs?' },
        { t: 'p', text: 'Pfund und Dollar schwanken frei — der Kurs bewegt sich also im Tagesverlauf mit den Zinsentscheidungen der Bank of England und der Fed, Inflationsdaten und der globalen Marktstimmung. Deshalb lohnt ein Blick auf den Live-Mittelkurs, bevor du umrechnest.' },
        { t: 'h2', text: 'So rechnest du Pfund in Dollar um' },
        { t: 'ul', items: [
          'Gib den Betrag in britischen Pfund (GBP) ein.',
          'Lies sofort den umgerechneten Dollar-Wert (USD) zum Live-Kurs.',
          'Vergleiche den Mittelkurs mit dem deiner Bank oder Karte — die Differenz sind deine echten Kosten.',
        ] },
        { t: 'cta', text: 'Jetzt GBP in USD umrechnen' },
      ],
    },
    'usd-to-php': {
      title: 'USD in PHP: US-Dollar in philippinische Pesos umrechnen',
      description: 'Rechne USD in PHP mit Live-Kursen um. Sieh den heutigen Kurs vom Dollar zum philippinischen Peso — wichtig für Überweisungen — kostenlos.',
      excerpt: 'Du sendest Dollar auf die Philippinen? Hier ist der Live-Kurs USD zu PHP und wie du bei jeder Überweisung fairen Wert bekommst.',
      body: [
        { t: 'p', text: 'USD zu PHP ist eine der meistgesuchten Umrechnungen der Welt — getrieben von Millionen philippinischer Arbeitskräfte im Ausland, die Geld nach Hause schicken. Ob Überweisung, Freelance-Einkommen oder Reise: Hier ist der Live-Kurs Dollar–Peso und wie du seinen Wert schützt.' },
        { t: 'rate', base: 'USD', quote: 'PHP' },
        { t: 'h2', text: 'Warum der Kurs bei Überweisungen so wichtig ist' },
        { t: 'p', text: 'Bei Überweisungen kostet der Wechselkurs meist mehr als die sichtbare Gebühr. Ein Dienst, der einen Kurs nur 2 % unter dem Mittelkurs anbietet, behält still 2 % von allem, was du sendest. Bei monatlichen Überweisungen summiert sich das übers Jahr zu echtem Geld.' },
        { t: 'h2', text: 'So bekommst du fairen Wert bei USD zu PHP' },
        { t: 'ul', items: [
          'Prüfe vor dem Senden den Live-Mittelkurs USD/PHP — er ist dein Maßstab.',
          'Vergleiche den Kurs deines Überweisungsdienstes damit, nicht nur die Gebühr.',
          'Rechne zuerst den genauen Betrag um, damit du weißt, wie viele Pesos ankommen sollten.',
        ] },
        { t: 'cta', text: 'Jetzt USD in PHP umrechnen' },
      ],
    },
  },
  pt: {
    'how-to-convert-currency': {
      title: 'Como converter moedas: um guia simples para 2026',
      description: 'Aprenda a converter moedas de forma fácil. Entenda as taxas de câmbio, a taxa média de mercado e como converter qualquer valor na hora com um conversor de moedas grátis.',
      excerpt: 'As taxas de câmbio podem parecer confusas. Este é um guia claro para converter moedas corretamente e evitar os custos ocultos que quase todos ignoram.',
      body: [
        { t: 'p', text: 'Seja viajando, comprando online ou enviando dinheiro para o exterior, converter moedas é algo que quase todos fazem. Mas as taxas de câmbio mudam o tempo todo, e o número que o seu banco mostra raramente é a taxa “real”. Este guia explica como a conversão de moedas funciona de verdade e como converter qualquer valor em segundos.' },
        { t: 'h2', text: 'O que é conversão de moedas?' },
        { t: 'p', text: 'Converter moedas é simplesmente expressar o valor de uma moeda em outra. Se 1 dólar americano equivale a 0,92 euro, converter 100 USD dá 92 EUR. O número que liga as duas moedas é a taxa de câmbio.' },
        { t: 'h2', text: 'Entendendo as taxas de câmbio' },
        { t: 'p', text: 'As taxas de câmbio mudam ao longo do dia conforme a oferta e a procura nos mercados globais. A referência mais justa é a taxa média de mercado: o ponto médio entre o preço de compra e de venda em que os bancos negociam. Um bom conversor mostra essa taxa média para você sempre saber o valor real.' },
        { t: 'rate', base: 'USD', quote: 'EUR' },
        { t: 'h2', text: 'Como converter moedas, passo a passo' },
        { t: 'ul', items: [
          'Escolha a moeda que você tem (sua moeda base).',
          'Escolha a moeda para a qual quer converter.',
          'Digite o valor: o resultado convertido atualiza na hora.',
          'Confira a taxa média de mercado para saber o valor real antes de pagar.',
        ] },
        { t: 'h2', text: 'Cuidado com as taxas ocultas' },
        { t: 'p', text: 'Bancos, casas de câmbio de aeroporto e muitos apps adicionam uma margem sobre a taxa média, além de tarifas fixas. Esse spread pode custar 3–6% sem você perceber. Compare sempre a taxa oferecida com a taxa média de mercado: se a diferença for grande, você está pagando a mais.' },
        { t: 'cta', text: 'Converta qualquer moeda com a taxa média de mercado ao vivo' },
      ],
    },
    'best-free-currency-converter-apps': {
      title: 'Os melhores apps grátis de conversão de moedas em 2026',
      description: 'Procurando o melhor conversor de moedas grátis? Veja o que realmente importa: taxas ao vivo, conversão de várias moedas, modo offline, sem anúncios nem rastreio.',
      excerpt: 'Nem todo conversor de moedas é igual. Veja o que procurar em um conversor grátis, e por que o simples, privado e rápido vence.',
      body: [
        { t: 'p', text: 'Procure por um conversor de moedas e você encontrará centenas de apps, a maioria cheia de anúncios, cadastros e rastreadores. Um bom conversor deveria fazer uma coisa muito bem: mostrar o valor real do seu dinheiro, na hora. Veja o que procurar.' },
        { t: 'h2', text: 'O que faz um bom conversor de moedas?' },
        { t: 'ul', items: [
          'Taxas ao vivo atualizadas diariamente a partir de uma fonte confiável.',
          'Taxa média de mercado, não uma taxa bancária com margem.',
          'Várias moedas ao mesmo tempo, para comparar de relance.',
          'Uma calculadora integrada para contas rápidas enquanto converte.',
          'Funciona offline usando taxas salvas.',
          'Sem anúncios, sem cadastro e sem rastreio.',
        ] },
        { t: 'h2', text: 'Por que criamos o Multi Converter' },
        { t: 'p', text: 'O Multi Converter mostra mais de 100 moedas se atualizando juntas enquanto você digita, inclui uma calculadora integrada e não guarda nada sobre você. É grátis para sempre, sem anúncios e sem conta: é só abrir e converter.' },
        { t: 'rate', base: 'USD', quote: 'GBP' },
        { t: 'cta', text: 'Experimente o conversor de moedas grátis' },
      ],
    },
    'what-is-mid-market-exchange-rate': {
      title: 'O que é a taxa média de mercado? (E por que importa)',
      description: 'A taxa média de mercado é a taxa de câmbio real e mais justa. Saiba o que é, por que os bancos cobram mais e como usá-la para não pagar a mais nas conversões.',
      excerpt: 'Você provavelmente já viu o termo “taxa média de mercado”. É a taxa de câmbio real, e conhecê-la pode economizar dinheiro em cada conversão.',
      body: [
        { t: 'p', text: 'Quando você lê “1 USD = 0,92 EUR”, esse número geralmente é a taxa média de mercado. É o número mais útil da conversão de moedas e, ainda assim, quase ninguém realmente paga por ele. Veja o que significa.' },
        { t: 'h2', text: 'A taxa média de mercado, definida' },
        { t: 'p', text: 'A cada momento, as moedas são compradas e vendidas a preços ligeiramente diferentes: o de compra (bid) e o de venda (ask). A taxa média de mercado é o ponto médio entre os dois. É a taxa que os bancos usam entre si, por isso é considerada a taxa de câmbio real e justa.' },
        { t: 'rate', base: 'EUR', quote: 'USD' },
        { t: 'h2', text: 'Por que o seu banco cobra mais' },
        { t: 'p', text: 'Bancos e apps de dinheiro partem da taxa média de mercado e adicionam uma margem: o lucro deles. Também podem cobrar tarifas fixas. Por isso o valor que você recebe quase sempre é menor do que um cálculo pela taxa média sugere.' },
        { t: 'h2', text: 'Como usá-la a seu favor' },
        { t: 'ul', items: [
          'Confira sempre a taxa média de mercado antes de trocar dinheiro.',
          'Compare-a com a taxa que o seu banco ou app oferece.',
          'Se a diferença passar de 1–2%, procure uma opção mais barata.',
        ] },
        { t: 'cta', text: 'Veja as taxas médias de mercado ao vivo para qualquer par' },
      ],
    },
    'convert-usd-to-inr': {
      title: 'USD para INR: converter dólares americanos em rupias indianas',
      description: 'Converta USD para INR com taxas ao vivo. Veja a taxa de hoje do dólar americano para a rupia indiana e converta dólares em rupias na hora e de graça.',
      excerpt: 'Convertendo dólares americanos em rupias indianas? Aqui está a taxa USD para INR ao vivo e como converter qualquer valor.',
      body: [
        { t: 'p', text: 'USD para INR — o dólar americano frente à rupia indiana — é uma das conversões mais procuradas do mundo. De remessas e trabalho freelance a viagens e compras online, milhões de pessoas precisam converter dólares em rupias todos os dias. Aqui está a taxa ao vivo e como fazer.' },
        { t: 'rate', base: 'USD', quote: 'INR' },
        { t: 'h2', text: 'O que move a taxa USD/INR?' },
        { t: 'p', text: 'A rupia indiana flutua frente ao dólar, então a taxa USD para INR muda diariamente conforme os juros, a inflação, o preço do petróleo e a procura por dólares. Como ela se move, vale conferir uma taxa média de mercado ao vivo antes de converter ou enviar dinheiro.' },
        { t: 'h2', text: 'Como converter dólares em rupias' },
        { t: 'ul', items: [
          'Digite o valor em dólares americanos (USD).',
          'Leia na hora o valor convertido em rupias indianas (INR) pela taxa ao vivo.',
          'Compare a taxa média de mercado com a do seu banco ou serviço de transferência: a diferença é o seu custo real.',
        ] },
        { t: 'p', text: 'Em remessas, sobretudo, mesmo uma diferença de 1–2% na taxa se acumula. Compare sempre primeiro com a taxa média de mercado.' },
        { t: 'cta', text: 'Converter USD para INR agora' },
      ],
    },
    'eur-to-usd': {
      title: 'EUR para USD: converter euros em dólares americanos',
      description: 'Converta EUR para USD com taxas ao vivo. Veja a taxa de hoje do euro para o dólar americano e converta euros em dólares na hora e de graça.',
      excerpt: 'Convertendo euros em dólares americanos? Aqui está a taxa EUR para USD ao vivo e como converter qualquer valor em segundos.',
      body: [
        { t: 'p', text: 'EUR/USD — o euro frente ao dólar americano — é o par de moedas mais negociado do mundo. Se você compra em lojas dos EUA, recebe em dólares ou viaja entre a Europa e os Estados Unidos, vai precisar converter euros em dólares. Aqui está a taxa ao vivo e como fazer.' },
        { t: 'rate', base: 'EUR', quote: 'USD' },
        { t: 'h2', text: 'Sobre o par EUR/USD' },
        { t: 'p', text: 'Diferente de uma moeda com câmbio fixo, o EUR/USD flutua livremente, então a taxa se move ao longo do dia conforme os juros, a inflação e a procura global. Por isso vale conferir uma taxa média de mercado ao vivo antes de converter ou trocar dinheiro.' },
        { t: 'h2', text: 'Como converter euros em dólares' },
        { t: 'ul', items: [
          'Digite o valor em euros (EUR).',
          'Leia na hora o valor convertido em dólares americanos (USD).',
          'Compare a taxa média de mercado com a do seu banco ou cartão.',
        ] },
        { t: 'cta', text: 'Converter EUR para USD agora' },
      ],
    },
    'best-exchange-rate-travel': {
      title: 'Como conseguir a melhor taxa de câmbio em viagens',
      description: 'Vai viajar para o exterior? Aprenda a conseguir a melhor taxa de câmbio, evitar casas de câmbio de aeroporto e tarifas ocultas de cartão, e usar a taxa média de mercado para economizar.',
      excerpt: 'Casas de câmbio de aeroporto e tarifas de cartão consomem o seu dinheiro de viagem sem você perceber. Veja como conseguir a melhor taxa de câmbio no exterior.',
      body: [
        { t: 'p', text: 'Trocar dinheiro em viagens é onde mais se perde com taxas ruins e tarifas ocultas. Alguns hábitos simples podem economizar dinheiro de verdade em cada viagem. Veja como conseguir a melhor taxa de câmbio no exterior.' },
        { t: 'h2', text: 'Conheça primeiro a taxa média de mercado' },
        { t: 'p', text: 'Antes de trocar qualquer coisa, confira a taxa média de mercado: a taxa real e justa. É a sua referência. Se uma casa de câmbio ou cartão oferecer algo muito pior, você saberá que deve recusar.' },
        { t: 'rate', base: 'USD', quote: 'EUR' },
        { t: 'h2', text: 'Evite as piores opções' },
        { t: 'ul', items: [
          'Casas de câmbio de aeroporto e de hotel: oferecem algumas das piores taxas que existem.',
          '“Conversão dinâmica de moeda”: quando a maquininha oferece cobrar na sua moeda, escolha sempre a moeda local.',
          'Sacar valores pequenos várias vezes, o que acumula tarifas fixas de caixa eletrônico.',
        ] },
        { t: 'h2', text: 'Formas inteligentes de pagar no exterior' },
        { t: 'ul', items: [
          'Use um cartão que aplique a taxa média de mercado sem tarifa de transação internacional.',
          'Saque valores maiores com menos frequência para reduzir tarifas fixas.',
          'Confira sempre o valor convertido em relação à taxa média de mercado antes de confirmar.',
        ] },
        { t: 'cta', text: 'Confira as taxas ao vivo antes de viajar' },
      ],
    },
    'money-converter-guide': {
      title: 'Conversor de dinheiro: como converter qualquer moeda do mundo',
      description: 'Procurando um conversor de dinheiro universal? Aprenda a converter dinheiro entre duas moedas quaisquer instantaneamente, de graça, com taxas ao vivo.',
      excerpt: 'Um conversor de dinheiro universal deveria lidar com qualquer par de moedas, não só as populares. Veja como converter dinheiro corretamente entre duas moedas quaisquer.',
      body: [
        { t: 'p', text: 'A maioria dos "conversores de dinheiro" só lida bem com um punhado de moedas importantes. Mas o dinheiro circula entre todo tipo de par: baht tailandês para peso mexicano, naira nigeriana para iene japonês, lira turca para rand sul-africano. Um conversor verdadeiramente universal deveria lidar com qualquer par instantaneamente, com a mesma precisão do USD/EUR.' },
        { t: 'h2', text: 'O que torna um conversor "universal"' },
        { t: 'ul', items: [
          'Suporte para mais de 100 moedas, não só as 10 mais populares.',
          'Conversão direta entre duas moedas quaisquer, não só de/para USD.',
          'Taxas médias de mercado ao vivo, atualizadas diariamente, para cada par.',
          'Sem bloqueio regional, sem moedas menores ausentes.',
        ] },
        { t: 'rate', base: 'GBP', quote: 'JPY' },
        { t: 'h2', text: 'Como funciona de verdade a conversão entre moedas' },
        { t: 'p', text: 'Nos bastidores, a maioria das taxas é calculada por meio de uma moeda de referência comum (geralmente o USD). Para converter GBP em JPY, um conversor pega a taxa GBP→USD e a taxa USD→JPY e as combina; você nunca vê essa etapa, só vê GBP→JPY diretamente. O Multi Converter faz isso automaticamente para cada moeda da sua lista, então qualquer par que você escolher simplesmente funciona.' },
        { t: 'h2', text: 'Como converter dinheiro entre duas moedas quaisquer' },
        { t: 'ul', items: [
          'Escolha sua moeda de partida e a moeda desejada.',
          'Digite o valor: o valor convertido atualiza na hora, seja qual for o par.',
          'Confira a taxa média de mercado como referência justa antes de pagar ou transferir.',
        ] },
        { t: 'cta', text: 'Converta qualquer moeda do mundo, de graça' },
      ],
    },
    'what-affects-exchange-rate': {
      title: 'O que afeta a taxa de câmbio? 5 fatores que movem as moedas',
      description: 'Por que as taxas de câmbio mudam todos os dias? Conheça os 5 principais fatores que movem o preço das moedas, dos juros à inflação.',
      excerpt: 'As taxas de câmbio nunca ficam paradas. Aqui estão os 5 fatores reais que movem a taxa entre duas moedas quaisquer, explicados de forma simples.',
      body: [
        { t: 'p', text: 'Abra um conversor de moedas em dois dias diferentes e a taxa quase nunca é exatamente igual. As taxas de câmbio se movem o tempo todo: aqui estão os cinco maiores motivos, sem jargão técnico.' },
        { t: 'rate', base: 'USD', quote: 'JPY' },
        { t: 'h2', text: '1. As taxas de juros' },
        { t: 'p', text: 'Quando o banco central de um país sobe os juros, o dinheiro tende a fluir para essa moeda em busca de retornos melhores, empurrando seu valor para cima. Decisões do Fed, do BCE ou do Banco da Inglaterra estão entre os maiores motores individuais das taxas de câmbio.' },
        { t: 'h2', text: '2. A inflação' },
        { t: 'p', text: 'Uma inflação mais alta corrói o poder de compra de uma moeda, o que costuma enfraquecê-la frente a moedas com preços mais estáveis. Diferenças persistentes de inflação entre dois países são um motor de longo prazo da sua taxa de câmbio.' },
        { t: 'h2', text: '3. Dados econômicos e crescimento' },
        { t: 'p', text: 'Bons números de emprego, crescimento do PIB ou comércio tendem a apoiar uma moeda, enquanto dados fracos a derrubam: os mercados reprecificam moedas constantemente com base no retrato econômico mais recente.' },
        { t: 'h2', text: '4. Estabilidade política e apetite por risco' },
        { t: 'p', text: 'Moedas de países politicamente estáveis costumam ser vistas como mais seguras. Eleições, mudanças de política ou tensões geopolíticas podem causar oscilações rápidas quando investidores movem dinheiro em direção ou para longe do risco percebido.' },
        { t: 'h2', text: '5. Oferta, demanda e fluxos comerciais' },
        { t: 'p', text: 'Um país que exporta bem mais do que importa costuma ver demanda constante pela sua moeda (compradores precisam dela para pagar bens), o que pode sustentar seu valor com o tempo — e o contrário para economias muito importadoras.' },
        { t: 'h2', text: 'Por que isso importa para você' },
        { t: 'p', text: 'Você não precisa acompanhar os cinco fatores, mas saber que as taxas se movem por razões reais (não ao acaso) explica por que a taxa de hoje pode ser diferente amanhã, e por que conferir uma taxa ao vivo antes de converter ou enviar dinheiro sempre vale mais que confiar em um número antigo de memória.' },
        { t: 'cta', text: 'Confira a taxa de conversão ao vivo de hoje' },
      ],
    },
    'gbp-to-usd': {
      title: 'GBP para USD: converter libras esterlinas em dólares americanos',
      description: 'Converta GBP para USD com taxas ao vivo. Veja a taxa de hoje da libra esterlina para o dólar americano e converta libras em dólares de graça.',
      excerpt: 'Convertendo libras esterlinas em dólares? Aqui está a taxa GBP para USD ao vivo e como converter qualquer valor em segundos.',
      body: [
        { t: 'p', text: 'GBP/USD — conhecido nos mercados como “cable” — é um dos pares de moedas mais antigos e negociados do mundo. Se você compra em lojas dos EUA, recebe em dólares ou viaja entre Londres e Nova York, aqui está a taxa libra-dólar ao vivo e como convertê-la.' },
        { t: 'rate', base: 'GBP', quote: 'USD' },
        { t: 'h2', text: 'O que move a taxa GBP/USD?' },
        { t: 'p', text: 'Tanto a libra quanto o dólar flutuam livremente, então a taxa se move ao longo do dia com as decisões de juros do Banco da Inglaterra e do Fed, dados de inflação e o sentimento global. Por isso vale conferir uma taxa média de mercado ao vivo antes de converter.' },
        { t: 'h2', text: 'Como converter libras em dólares' },
        { t: 'ul', items: [
          'Digite o valor em libras esterlinas (GBP).',
          'Leia na hora o valor convertido em dólares (USD) pela taxa ao vivo.',
          'Compare a taxa média de mercado com a do seu banco ou cartão: a diferença é o seu custo real.',
        ] },
        { t: 'cta', text: 'Converter GBP para USD agora' },
      ],
    },
    'usd-to-php': {
      title: 'USD para PHP: converter dólares americanos em pesos filipinos',
      description: 'Converta USD para PHP com taxas ao vivo. Veja a taxa de hoje do dólar para o peso filipino — essencial para remessas — e converta de graça.',
      excerpt: 'Enviando dólares para as Filipinas? Aqui está a taxa USD para PHP ao vivo e como garantir valor justo em cada transferência.',
      body: [
        { t: 'p', text: 'USD para PHP é uma das conversões mais procuradas do mundo, impulsionada por milhões de trabalhadores filipinos no exterior que enviam dinheiro para casa. Sejam remessas, renda freelance ou viagem, aqui está a taxa dólar-peso ao vivo e como proteger o seu valor.' },
        { t: 'rate', base: 'USD', quote: 'PHP' },
        { t: 'h2', text: 'Por que a taxa importa tanto nas remessas' },
        { t: 'p', text: 'Nas remessas, a taxa de câmbio costuma custar mais do que a tarifa visível. Um serviço que oferece uma taxa apenas 2% abaixo da média de mercado fica silenciosamente com 2% de tudo o que você envia. Em um ano de envios mensais, isso vira dinheiro de verdade.' },
        { t: 'h2', text: 'Como obter valor justo no USD para PHP' },
        { t: 'ul', items: [
          'Confira a taxa média USD/PHP ao vivo antes de enviar: é a sua referência.',
          'Compare a taxa do seu serviço de remessas com ela, não só a tarifa.',
          'Converta primeiro o valor exato para saber quantos pesos devem chegar.',
        ] },
        { t: 'cta', text: 'Converter USD para PHP agora' },
      ],
    },
  },
}

export function getLocalizedPost(lang: string, slug: string): LocalizedPost | undefined {
  return LOCALIZED[lang]?.[slug]
}

export function getBlogUI(lang: string) {
  return BLOG_UI[lang] ?? BLOG_UI.en
}
